export default {
  title: "Employee List",
  addEmployee: "Add Employee",
  editEmployee: "Edit Employee",
  deleteConfirmation: "Are you sure you want to delete this employee?",
  searchPlaceholder: "Search employees...",
  paginationNext: "Next",
  paginationPrevious: "Previous",
  employmentDate: "Date of Employment",
  dateOfBirth: "Date of Birth",
  email: "Email",
  phone: "Phone",
  updateEmployee: "Update Employee",
  listView: "List",
  tableView: "Table",

  firstName: "First Name",
  lastName: "Last Name",
  department: "Department",
  position: "Position",
  actions: "Actions",
  edit: "Edit",
  delete: "Delete",
  confirmDelete: "Are you sure you want to delete this employee?",
  searchPlaceholder: "Search employees...",
  yes: "Yes",
  no: "No",

  firstNameRequired: "First name is required.",
  lastNameRequired: "Last name is required.",
  emailRequired: "Email is required.",
  phoneRequired: "Phone number is required.",
  departmentRequired: "Department is required.",
  positionRequired: "Position is required.",
  employmentDateRequired: "Employment date is required.",
  dateOfBirthRequired: "Date of birth is required.",
  confirmSubmit: "Confirm Submission",
  areYouSureSubmit: "Are you sure you want to update?",
  yes: "Yes",
  no: "No",
  employeeUpdated: "Updated successfully.",
  employeeAdded: "Added successfully.",
};
