export default {
  title: "Çalışan Listesi",
  addEmployee: "Çalışan Ekle",
  editEmployee: "Çalışan Düzenle",
  deleteConfirmation: "Bu çalışanı silmek istediğinize emin misiniz?",
  searchPlaceholder: "Çalışanları ara...",
  paginationNext: "İleri",
  paginationPrevious: "Geri",
  employmentDate: "İşe Giriş Tarihi",
  dateOfBirth: "Doğum Tarihi",
  email: "Email",
  phone: "Telefon",
  updateEmployee: "Bilgileri Güncelle",

  firstName: "İsim",
  lastName: "Soyad",
  department: "Departman",
  position: "Pozisyon",
  actions: "Aksiyon",
  edit: "Düzenle",
  delete: "Sil",
  confirmDelete: "Bu çalışanı silmek istediğinizden emin misiniz?",
  searchPlaceholder: "Çalışanlarda ara..",
  yes: "Evet",
  no: "Hayır",
  listView: "Liste",
  tableView: "Tablo",
  firstNameRequired: "İsim gerekli.",
  lastNameRequired: "Soyad gerekli.",
  emailRequired: "Email gerekli",
  phoneRequired: "Numara gerekli",
  departmentRequired: "Departman seçiniz",
  positionRequired: "Posizyon seçiniz",
  employmentDateRequired: "Tarih giriniz.",
  dateOfBirthRequired: "Tarih giriniz.",
  confirmSubmit: "Onaylıyor musunuz?",
  areYouSureSubmit: "Bilgiler güncellensin mi?",
  yes: "Evet",
  no: "Hayır",
  employeeUpdated: "Başarılı bir şekilde güncellendi.",
  employeeAdded: "Başarılı bir şekilde eklendi.",
};
